default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: dental_controle_development

test:
  <<: *default
  database: dental_controle_test


production:
  <<: *default
  database: dental_controle_production
  username: dental_controle
  password: <%= ENV['DENTAL_CONTROLE_DATABASE_PASSWORD'] %>
